### ISSUE TITLE
Compressed .ark files

### ISSUE THREAD

**Issue by razor1179** [srvk/eesen#113]
Hi,

I am currently trying to train the RNN using Tensorflow, but with the features extracted from EESEN. I would like to know if there is any change I can make to the codes used to obtain the features such that the .ark files created are not compressed?

Regards,
Deepak

**Comment by riebling** [comment]
yes you would use a different wspecifier (see [Kaldi IO mechanisms](http://kaldi-asr.org/doc/io.html#io_sec_specifiers)) that specifies to output to an uncompressed file. An example of a wspecifier that writes to an archive (ark) in text format is: "ark,t:/tmp/new_features.ark". The compressed ark format is gzip so you could use gunzip to uncompress. You could also use the "copy-feats" program to convert formats. Here's an [example](https://sourceforge.net/p/kaldi/discussion/1355348/thread/e3717690/?limit=25) of doing the opposite direction (text to compressed binary format)
