### ISSUE TITLE
FAIL: failed: Dim() == v.Dim()

### ISSUE THREAD

**Issue by MattGjdr** [srvk/eesen#124]
I am trying to make script for training on timit but I am getting error. What am I doing wrong?

train-ctc-parallel --report-step=1000 --num-sequence=10 --frame-limit=25000 --learn-rate=0.00004 --momentum=0.9 --verbose=1 'ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l4_c320/train.scp ark:- | add-deltas ark:- ark:- |' 'ark:gunzip -c exp/train_phn_l4_c320/labels.tr.gz|' exp/train_phn_l4_c320/nnet/nnet.iter0 exp/train_phn_l4_c320/nnet/nnet.iter1
add-deltas ark:- ark:-
apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l4_c320/train.scp ark:-
LOG (train-ctc-parallel:main():train-ctc-parallel.cc:124) TRAINING STARTED
KALDI_ASSERT: at train-ctc-parallel:CopyFromVec:vector.cc:199, failed: Dim() == v.Dim()
Stack trace is:
eesen::KaldiGetStackTrace()
eesen::KaldiAssertFailure_(char const*, char const*, int, char const*)
eesen::VectorBase<float>::CopyFromVec(eesen::VectorBase<float> const&)
train-ctc-parallel(main+0x114b) [0x47afb2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7faf018aab45]
train-ctc-parallel() [0x478969]

All data files looks good. 

Thanks for help.

**Comment by MattGjdr** [comment]
I think i fixed it.

**Comment by icestoneking** [comment]
> I am trying to make script for training on timit but I am getting error. What am I doing wrong?
> 
> train-ctc-parallel --report-step=1000 --num-sequence=10 --frame-limit=25000 --learn-rate=0.00004 --momentum=0.9 --verbose=1 'ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l4_c320/train.scp ark:- | add-deltas ark:- ark:- |' 'ark:gunzip -c exp/train_phn_l4_c320/labels.tr.gz|' exp/train_phn_l4_c320/nnet/nnet.iter0 exp/train_phn_l4_c320/nnet/nnet.iter1
> add-deltas ark:- ark:-
> apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l4_c320/train.scp ark:-
> LOG (train-ctc-parallel:main():train-ctc-parallel.cc:124) TRAINING STARTED
> KALDI_ASSERT: at train-ctc-parallel:CopyFromVec:vector.cc:199, failed: Dim() == v.Dim()
> Stack trace is:
> eesen::KaldiGetStackTrace()
> eesen::KaldiAssertFailure_(char const*, char const*, int, char const*)
> eesen::VectorBase::CopyFromVec(eesen::VectorBase const&)
> train-ctc-parallel(main+0x114b) [0x47afb2]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7faf018aab45]
> train-ctc-parallel() [0x478969]
> 
> All data files looks good.
> 
> Thanks for help.

hi,Is this question solved? Looking forward to your reply？
Best wishes
