### ISSUE TITLE
without MVN

### ISSUE THREAD

**Issue by double22a** [srvk/eesen#126]
There is a bad result by adding MVN to input feature. What causes this phenomenon?

Thank you.

**Comment by fmetze** [comment]
what is mvn?

**Comment by double22a** [comment]
The global mean and variance normalization (MVN) is applied on input feature vectors.

**Comment by fmetze** [comment]
Maybe the estimation is not running correctly, or some other problem in the estimation. Hard to say without any other information.

**Comment by double22a** [comment]
Thanks
