### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by zyb8543d** [srvk/eesen#176]
mkdir: cannot create directory ‘build’: File exists
gcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -c /home/yunbin
.zhang/eesen/tools/ATLAS/build/..//CONFIG/src/atlconf_misc.cgcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -o xconfig /hom
e/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/src/config.c atlconf_misc.o /tmp/cc8nyqqd.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'./xconfig -d s /home/yunbin.zhang/eesen/tools/ATLAS/build/../ -d b /home/yunbin.zhang/eese
n/tools/ATLAS/build probe_OS.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'
OS configured as Linux (1)
probe_asm.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'
Assembly configured as GAS_x8664 (2)
probe_vec.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'
Vector ISA Extension configured as  SSE3 (6,448)
probe_arch.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'
Architecture configured as  PII (18)
/tmp/ccpW77vq.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'
Clock rate configured as 2399Mhz

Maximum number of threads configured as  28
probe_pmake.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'Parallel make command configured as '$(MAKE) -j 28'
Cannot detect CPU throttling.
gcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -o xisgcc /home
/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/src/IsGcc.c atlconf_misc.o /tmp/cc2IakgI.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'gcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -c /home/yunbin
.zhang/eesen/tools/ATLAS/build/..//CONFIG/src/probe_comp.cgcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -o xprobe_comp 
probe_comp.o atlconf_misc.o probe_comp.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'rm -f config1.out
make atlas_run atldir=/home/yunbin.zhang/eesen/tools/ATLAS/build exe=xprobe_comp redir=con
fig1.out \                args="-v 0 -o atlconf.txt -O 1 -A 18 -Si nof77 0 -V 448   -b 64 -d b /home
/yunbin.zhang/eesen/tools/ATLAS/build"make[1]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build ; ./xprobe_comp -v 0 -o atlconf.txt -O 1 -A 
18 -Si nof77 0 -V 448   -b 64 -d b /home/yunbin.zhang/eesen/tools/ATLAS/build > config1.outprobe_f2c.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'make[1]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
cat config1.out
REPORTED: res=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/libgfortran.so

gcc -I/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include  -g -w -o xspew /home/
yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/src/SpewMakeInc.c atlconf_misc.o \               
/tmp/ccvLxI9G.o: In function `ATL_tmpnam':
/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG/include/atlas_sys.h:224: warning: th
e use of `tmpnam' is dangerous, better use `mkstemp'rm -f *core* *.o config?.out
mkdir src bin tune interfaces
mkdir: cannot create directory ‘src’: File exists
mkdir: cannot create directory ‘bin’: File exists
mkdir: cannot create directory ‘tune’: File exists
mkdir: cannot create directory ‘interfaces’: File exists
make: *** [make_subdirs] Error 1
make -f Make.top startup
make[1]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make -f Make.top leafstart leaf=interfaces/lapack/C2F/src
make[2]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
cd interfaces/lapack/C2F/src ; ln -s /home/yunbin.zhang/eesen/tools/ATLAS/build/Make.inc M
ake.incln: failed to create symbolic link ‘Make.inc’: File exists
make[2]: *** [leafstart] Error 1
make[2]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make[1]: *** [startup] Error 2
make[1]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make: *** [startup] Error 2
DONE configure
make -f Make.top build
make[1]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
cd bin/ ; make xatlas_build
make[2]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
make[2]: `xatlas_build' is up to date.
make[2]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
cd bin/ ; ./xatlas_build -1 0 -a 1 -l 1
make[2]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
make[2]: *** No rule to make target `/home/yunbin.zhang/eesen/tools/ATLAS/build/..//CONFIG
/ARCHS/PII64SSE3.tar.bz2', needed by `/home/yunbin.zhang/eesen/tools/ATLAS/build/ARCHS/PII64SSE3'.  Stop.make[2]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'

BEGIN STAGE 1-0-0: SYSTEM PROBE/AUX COMPILE at 10:21
make[2]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/auxil ; make -s ATL_buildinfo.o
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/auxil ; make lib
make[3]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/auxil'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1 ; make lib
make[4]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
make dgen
make[5]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
make Make_drot
make[6]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1 ; make dinstall_rot
make[7]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
rm -f GEN/*
./xrotsrch -p d
TST: make drottest urout=rot1_x0y0.c opt=" -X 4 1 -1 2 -3 -Y 4 1 -1 3 -2" 
make[8]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing ; make lib
make[8]: *** read jobs pipe EOF.  Stop.
make[8]: *** Waiting for unfinished jobs....
make[9]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make -j 28 dlib.grd
make[9]: *** read jobs pipe EOF.  Stop.
make[9]: *** Waiting for unfinished jobs....
make[10]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[10]: warning: -jN forced in submake: disabling jobserver mode.
make[10]: `dlib.grd' is up to date.
make[10]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[9]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[8]: *** [tstlib.grd] Error 2
make[8]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
TST: make drottest urout=rot1_x1y1.c opt="" 
make[8]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing ; make lib
make[8]: *** read jobs pipe EOF.  Stop.
make[8]: *** Waiting for unfinished jobs....
make[9]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make -j 28 dlib.grd
make[9]: *** read jobs pipe EOF.  Stop.
make[9]: *** Waiting for unfinished jobs....
make[10]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[10]: warning: -jN forced in submake: disabling jobserver mode.
make[10]: `dlib.grd' is up to date.
make[10]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[9]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[8]: *** [tstlib.grd] Error 2
make[8]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
TST: make drottest urout=rot4_x1y1.c opt="" 
make[8]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing ; make lib
make[8]: *** read jobs pipe EOF.  Stop.
make[8]: *** Waiting for unfinished jobs....
make[9]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make -j 28 dlib.grd
make[9]: *** read jobs pipe EOF.  Stop.
make[9]: *** Waiting for unfinished jobs....
make[10]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[10]: warning: -jN forced in submake: disabling jobserver mode.
make[10]: `dlib.grd' is up to date.
make[10]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[9]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/testing'
make[8]: *** [tstlib.grd] Error 2
make[8]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
NO GENERAL CASE SURVIVED!!  ABORTING!!
  ID  incX  incY  alpha  beta  ROUT
====  ====  ====  =====  ====  =============
   1     0     0     2     2  rot1_x0y0.c
   2     1     1     2     2  rot1_x1y1.c
   3     1     1     2     2  rot4_x1y1.c

make[7]: *** [dinstall_rot] Error 255
make[7]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/tune/blas/level1'
make[6]: *** [Make_drot] Error 2
make[6]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
make[5]: *** [dgen] Error 2
make[5]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
make[4]: *** [dlib] Error 2
make[4]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/blas/level1'
make[3]: *** [lib.grd] Error 2
make[3]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/src/auxil'
make[2]: *** [IStage1] Error 2
make[2]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
ERROR 621 DURING CACHESIZE SEARCH!!.  CHECK INSTALL_LOG/Stage1.log FOR DETAILS.
make[2]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
cd /home/yunbin.zhang/eesen/tools/ATLAS/build ; make error_report
make[3]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make -f Make.top error_report
make[4]: Entering directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
uname -a 2>&1 >> bin/INSTALL_LOG/ERROR.LOG
/usr/bin/gcc -v 2>&1  >> bin/INSTALL_LOG/ERROR.LOG
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/i
nfo --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linuxThread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
/usr/bin/gcc -V 2>&1  >> bin/INSTALL_LOG/ERROR.LOG
gcc: error: unrecognized command line option ‘-V’
gcc: fatal error: no input files
compilation terminated.
make[4]: [error_report] Error 4 (ignored)
/usr/bin/gcc --version 2>&1  >> bin/INSTALL_LOG/ERROR.LOG
tar cf error_PII64SSE3.tar Make.inc bin/INSTALL_LOG/*
bzip2 error_PII64SSE3.tar
bzip2: Output file error_PII64SSE3.tar.bz2 already exists.
make[4]: *** [error_report] Error 1
make[4]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make[3]: *** [error_report] Error 2
make[3]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make[2]: *** [error_report] Error 2
make[2]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build/bin'
cat: ../../CONFIG/error.txt: No such file or directory
cat: ../../CONFIG/error.txt: No such file or directory
make[1]: *** [build] Error 255
make[1]: Leaving directory `/home/yunbin.zhang/eesen/tools/ATLAS/build'
make: *** [build] Error 2

**Comment by fmetze** [comment]
This looks like a problem when building ATLAS? Hard to debug without any extra information. I would create a clean environment (new checkout) and try to run without parallelization (not use make -j)

**Comment by zyb8543d** [comment]
yes, when i run install_atlas.sh,met the error.

**Comment by riebling** [comment]
A work-around might be to install Atlas system-wide, such as with a package manager,
```
sudo apt-get install libatlas3-base libatlas-base-dev libatlas-dev
```
(This is how we provision virtual machines that install Eesen - but requires root privileges)

**Comment by zyb8543d** [comment]
I want to make sure that my operation is correct？
  cd tools
  sudo yum install libatlas3-base libatlas-base-dev libatlas-dev
but still exist some errors, otherwisse, my linux system is redhat not ubuntu.
**errors are as # follows:**
[root@node1 tools]# sudo yum install libatlas3-base libatlas-base-dev libatlas-dev
Loaded plugins: fastestmirror, langpacks
epel                                                               | 4.3 kB  00:00:00     
erlang-solutions                                                   |  951 B  00:00:00     
extras                                                             | 2.9 kB  00:00:00     
msxf                                                               | 2.9 kB  00:00:00     
nux-dextop                                                         | 2.9 kB  00:00:00     
nvidia-diag-driver-local-384.66                                    | 2.4 kB  00:00:00     
os                                                                 | 3.6 kB  00:00:00     
updates                                                            | 2.9 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * nux-dextop: li.nux.ro
No package libatlas3-base available.
No package libatlas-base-dev available.
No package libatlas-dev available.
Error: Nothing to do

**Comment by riebling** [comment]
ok sorry, I gave instructions specific to Ubuntu. Not sure of the Atlas package names on RedHat

**Comment by kidconan** [comment]
> I want to make sure that my operation is correct？
> cd tools
> sudo yum install libatlas3-base libatlas-base-dev libatlas-dev
> but still exist some errors, otherwisse, my linux system is redhat not ubuntu.
> **errors are as # follows:**
> [root@node1 tools]# sudo yum install libatlas3-base libatlas-base-dev libatlas-dev
> Loaded plugins: fastestmirror, langpacks
> epel | 4.3 kB 00:00:00
> erlang-solutions | 951 B 00:00:00
> extras | 2.9 kB 00:00:00
> msxf | 2.9 kB 00:00:00
> nux-dextop | 2.9 kB 00:00:00
> nvidia-diag-driver-local-384.66 | 2.4 kB 00:00:00
> os | 3.6 kB 00:00:00
> updates | 2.9 kB 00:00:00
> Loading mirror speeds from cached hostfile
> 
> * nux-dextop: li.nux.ro
>   No package libatlas3-base available.
>   No package libatlas-base-dev available.
>   No package libatlas-dev available.
>   Error: Nothing to do

Hey, have you solved this question? And what's your enviroment? centos7?
Now I meet the same difficulty in installing EESEN?
If you succed, could you tell how to solve it.

**Comment by fmetze** [comment]
closed for inactivity
