### ISSUE TITLE
OpenFST install hangs (forever?)

### ISSUE THREAD

**Issue by riebling** [srvk/eesen#180]
strange bug installing Eesen: there are 3 attempts to download OpenFST from different sources; the first 2 fail because the source http://openfst.cs.nyu.edu seems to be offline. Maybe we should specify timeouts, or reverse the order, such that the copy downloaded from openslr.org works right away. I looked up default timeouts for wget and curl which appear to be 7.5 and 5 minutes, respectively, but my Eesen build seems in fact to be taking "forever" to download openfst-1.4.1.tar.gz.

Ok, not forever :)  just took a really super long time (probably the default 12.5 minutes combined)

**Comment by efosler** [comment]
Just fixed by changing to http://www.openfst.org - looks like they changed the base server and the openfst.org server is likely to be more stable.  I can create a pull request if you want.

**Comment by riebling** [comment]
Oops, looks like this has been fixed, but the Issue was never closed:
https://github.com/srvk/eesen/commit/fa4bc292ed9f2ca6f6709fa158f53e11e494aeda
(I think I had some permissions trouble and asked Florian to fix it, but seems good)

**Comment by efosler** [comment]
Still relevant on branch tf_clean.
