### ISSUE TITLE
tf_clean swbd v1-tf: illegal argument batch_size passed from run_ctc_phn.sh

### ISSUE THREAD

**Issue by efosler** [srvk/eesen#189]
Trying a run straight out of the box on swbd, data prep went (mostly) fine (have one change I'll suggest at some point).  Ran into this with run_ctc_phn.sh

...
=====================================================================
                Training AM with the Full Set
=====================================================================
generating train labels...
generating cv labels...
steps/train_ctc_tf.sh --nlayer 4 --nhidden 320 --batch_size 16 --learn_rate 0.005 --half_after 6 --model deepbilstm --window 3 --ninitproj 80 --nproj 60 --nfinalproj 100 --norm false data/train_nodup data/train_dev exp/train_phn_l4_c320_mdeepbilstm_w3_nfalse_p60_ip80_fp80
steps/train_ctc_tf.sh: invalid option --batch_size

Sure enough, the train_ctc_tf.sh script does not define a default batch_size as well as learn_rate (may be lr_rate?), window, or norm.  Is there some sort of version skew between the scripts?

**Comment by efosler** [comment]
FWIW, it does look like run_ctc_char.sh has lr_rate rather than learn_rate, but also declares batch_size.

**Comment by ramonsanabria** [comment]
Hi,

Thanks for pointing this out. I think now should be solved (
https://github.com/srvk/eesen/commit/52d8974d1e5e43b51a309d05f44f55a39ec16f0e).
We had a version disagreement with train_ctc_tf.sh. There are few
parameters defined outside the .sh script and some in the python script
(that we pas as arguments straight away). We should come up with some type
of agreement. For now is clean but it would be good to have them either in
the python side or in the bash side.

Any thoughts/suggestions @fmetze @efosler ?

Also, please remember to change path.sh accordingly (i.e. add your hostname
in the path.sh with $PYTHONPATH and source your virtualenv).

Please keep us letting us know you experience with the tf_clean branch. I
am very happy to keep on solving possible bugs.

Thanks!


2018-06-21 13:26 GMT-04:00 Eric Fosler-Lussier <notifications@github.com>:
