### ISSUE TITLE
Missing label.counts

### ISSUE THREAD

**Issue by tony-stark1** [srvk/eesen#203]
Hi,

I'm trying to run the WSJ example it works up until it reaches this line of code:
gunzip -c $dir/labels.tr.gz | awk '{line=$0; gsub(" "," 0 ",line); print line " 0";}' | \
  analyze-counts --verbose=1 --binary=false ark:- $dir/label.counts >& $dir/log/compute_label_counts.log || exit 1

At that point it fails and according to the logs it is because it cannot find the label.counts file. I looked for the file and it doesn't seem to exist. 
I've tried looking through the code but I can't find where this file is created. 

greping the directory only show places where the file is used but not how to create it. 
Please let me know what to run to make this file or how to make it manually if that is the solution.

**Comment by riebling** [comment]
I think that file comes from here:
https://github.com/srvk/eesen/blob/4a98525fabf491c32317326fdca11f44ea9117f1/asr_egs/wsj/steps/train_ctc_parallel.sh#L114-L121

**Comment by tony-stark1** [comment]
So it looks like its failing to created the file due to this error:
ERROR (analyze-counts:ReadBasicType():base/io-funcs-inl.h:85) Read failure in ReadBasicType, file position is -1, next char is -1
WARNING (analyze-counts:Read():util/kaldi-holder-inl.h:255) BasicVectorHolder::Read, could not interpret line: 0 40 0 40 0 40 0 20 0 F 0 40 0 40 0

Which looks like something is going wrong when creating the labels.tr.gz file

**Comment by icestoneking** [comment]
> So it looks like its failing to created the file due to this error:
> ERROR (analyze-counts:ReadBasicType():base/io-funcs-inl.h:85) Read failure in ReadBasicType, file position is -1, next char is -1
> WARNING (analyze-counts:Read():util/kaldi-holder-inl.h:255) BasicVectorHolder::Read, could not interpret line: 0 40 0 40 0 40 0 20 0 F 0 40 0 40 0
> 
> Which looks like something is going wrong when creating the labels.tr.gz file

hi,Is this problem solved?I also have this problem.
