### ISSUE TITLE
Query on LibriSpeech Character Error Rate

### ISSUE THREAD

**Issue by Pradeep-Rangan** [srvk/eesen#204]
Hello Sir,

I have trained the end-to-end ASR on LibriSpeech corpus using the examples provided in the repository.  However the RESULTS are provided only for the phoneme based lexicon units at the output CTC layer. I have tried to repeat the experiments for character based CTC output by modifying the scripts (as given in asr_egs/wsj/local/wsj_prepare_char_dict.sh). However, the CER obtained is ~11% , and is greater than the WER (~8.6%). Is there anything I am missing in obtaining the actual CER? It would be of great help if the RESULTS section also reports the actual CER.

I hope you do the needful.

Thanking You

With Regards
Pradeep Rangan
PhD Scholar
Indian Institute of Technology Kharagpur

**Comment by fmetze** [comment]
The Character Error Rate (CER) is usually greater than the Word Error Rate (WER), and the character-based system will have higher error rates than the phone-based systems. I am not sure if someone has reference runs for these cases ready, and could provide them for addition to the README?

**Comment by Pradeep-Rangan** [comment]
Thanks for your information sir.
