### ISSUE TITLE
Cannot install openfst-1.4.1

### ISSUE THREAD

**Issue by JeromeNi** [srvk/eesen#215]
Hello, 

after cloning eesen, I went to tools directory and typed make. However, it was encountering an error when installing openfst-1.4.1

The error was shown as below:

./../include/fst/replace.h: In constructor 'fst::ArcIterator<fst::ReplaceFst<A, T, C> >::ArcIterator(const fst::ReplaceFst<A, T, C>&, fst::ArcIterator<fst::ReplaceFst<A, T, C> >::StateId)':
./../include/fst/replace.h:1253:57: error: expected ';' before '::' token
           ->template CacheBaseImpl<typename C::State, C>::InitArcIterator(
                                                         ^~
Makefile:328: recipe for target 'fst.lo' failed

I've attached a full output from terminal here
[out_make.txt](https://github.com/srvk/eesen/files/3614099/out_make.txt)

**Comment by AdolfVonKleist** [comment]
This is a known issue with older versions of openfst and recent version of
g++.  I encountered this last week with the same version of OpenFst,
although not in the context of eesen.  Following this patch fixed the issue
for me (ubuntu 18 + g++ 7.4):

https://github.com/hfst/hfst/commit/134d5a5aac3fd015c4955b6f5fdfede42159e402



2019年9月15日(日) 20:02 JeromeNi <notifications@github.com>:

**Comment by JeromeNi** [comment]
Thank you, the patch worked for me!
