### ISSUE TITLE
Why do we need space and unk symbols in the char mode for acoustic model?

### ISSUE THREAD

**Issue by wizardk** [srvk/eesen#218]

**Comment by ramonsanabria** [comment]
to know where a word ends.

**Comment by wizardk** [comment]
@ramonsanabria Hi, but let AM to learn where is the word segmentation is really reasonable? Sometimes this segmentation is not obvious. We are already using CTC, so the AM should not care for this and let LM to handle it.

Thanks for your reply and I'm really glad to discuss this issue with you.

**Comment by ramonsanabria** [comment]
Hi, those are just design choices. I has been shown that CTC can actually
model spaces. Please see:

https://arxiv.org/abs/1708.04469
https://arxiv.org/abs/1712.06855
https://ieeexplore.ieee.org/abstract/document/8639530

**Comment by wizardk** [comment]
@ramonsanabria Hi, good works in your papers! About space in AM, do you mean this part in [1708.04469](https://arxiv.org/abs/1708.04469)?
> Word boundaries can be modeled with a space symbol or by capitalizing the first letter of each word [11]. While decoding CTC acoustic models without adding external linguistic information works well, a vast amount of training data should be used to get competitive results [12].

Actually, this means the AM learned some linguistic information and embedded a weak LM in it from the labeled text. It's not a good ideal if we need to switch application domain by using corresponding LM. And it **IS** need a vast amount of training data in the meantime.

Thanks for your information again.

I only use this repository to build TLG and decode CTC outputs. I still wonder whether I can abandon these symbols in AM by using this repository? Do you have any ideal?

**Comment by wizardk** [comment]
@ramonsanabria I got it. I can train AM in char mode and build TLG in phone mode. In this way, I can discard space, unk, silence and so on.

**Comment by ramonsanabria** [comment]
correct yes.
