### ISSUE TITLE
script for TEDLIUM release2

### ISSUE THREAD

**Issue by jinserk** [srvk/eesen#27]
Hello. First of all, thank you very much for the great work!
I'm interested in the training of TEDLIUM, especially for the release2.
I guess there aren't no proper language model, so it needs to build my own language model from the corpus and dictionary using irstlm or srilm. Could you tell me how to do it? or any plan to add it?
Thanks!

**Comment by yajiemiao** [comment]
The best way is to use/adapt the language modeling training script from WSJ.
https://github.com/srvk/eesen/blob/master/asr_egs/wsj/local/wsj_train_lms.sh

Alternatively here is a script I used to create my customized TED language model. You may modify the directory (e.g., lang_bd, lang_test_bd_tgpr, etc.)
[train_lms.sh.zip](https://github.com/srvk/eesen/files/91980/train_lms.sh.zip)

**Comment by jinserk** [comment]
Sorry I didn't notice you answered. Thank you so much!
