### ISSUE TITLE
Running BLSTM without CTC 

### ISSUE THREAD

**Issue by basilabraham123** [srvk/eesen#32]
We found the scripts train-ce in essen netbin. Is there a recipe file using this script to run only BLSTM.

**Comment by yajiemiao** [comment]
We don't have recipes for CE training, as it's beyond the scope of Eesen. 
You may follow the same recipe for CTC training. The only difference is the switch of train_tool in train_ctc_parallel.sh from train-ctc-parallel to train-ce-parallel. However, you may need to tune the learning rate to find the best one for CE learning.

A major difference lies in the format of the alignment file. For CE, you have to provide frame-level labels. The labels of multiple utterances can be stored in a single text-formatted file, for example:
UTT1 4 4 9 9 9 9 10 32 32 32 65 0 0 0
UTT2 100 100 80 2 2 2 2 2 19 3 65 89 0 0 0
...

Each line starts with the utterance ID which is then followed by the label indexes (integers). They are delimited by spaces.

**Comment by basilabraham123** [comment]
Thank you sir
