### ISSUE TITLE
Support for multi-GPU

### ISSUE THREAD

**Issue by fernand** [srvk/eesen#40]
I know that multi-GPU is not supported yet. I'm interested in knowing whether supporting that is straightforward or not, so that we know it's worth for us to work on it.
We're interested using Eesen on more than 1000 hours of audio, so obviously that would be helpful (the 110 hours TEDLIUM dataset takes about 3 days with a single K40).
Thanks!

**Comment by gowayyed** [comment]
I should be working on that soon. It is not straightfoward, but doable within a month or two if you know where everything is. Basically, you need to take the natural gradient code from kaldi and integrate it with eesen. The main idea to get parallelization to work is to scale the gradients accordingly, which the natural gradient does, as described in this paper (http://arxiv.org/pdf/1410.7455v4.pdf). This paper is already implemented in kaldi, so all we need to do is to migrate that to eesen.

**Comment by migueljette** [comment]
Just out of curiosity, has anybody worked on this yet?
