### ISSUE TITLE
ctc label and token label mismatch

### ISSUE THREAD

**Issue by yingzha** [srvk/eesen#42]
Hi,

I noticed that in ctc labels, the 0 index denotes `<blk>`, but in token fst the 0 index becomes `<eps>` and the 1st index is `<blk>`, how do you solve this mismatch problem when decoding? I mean when you feed ctc ouputs to TLG.fst, the labels with the same index are different. Or you pass the character/phone output instead of label index into TLG.fst?

Thanks!

**Comment by yajiemiao** [comment]
the mismatch is solved here https://github.com/srvk/eesen/blob/master/src/decoder/decodable-matrix.h#L52

**Comment by yingzha** [comment]
Thanks a lot!
