### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by madhavsund** [srvk/eesen#43]
1.how to get the output of network in decoder, like Softmax  probability vs time stamp
2. How to get the phone level output

**Comment by al-muammar** [comment]
1. Look at `netbin/net-output-extract.cc`.
2. What do you mean by phone level output?

**Comment by yajiemiao** [comment]
For your question 1, look at line 77 of https://github.com/srvk/eesen/blob/master/asr_egs/wsj/steps/decode_ctc.sh

If you want to save the posteriors into text format, simply:
net-output-extract --class-frame-counts=$srcdir/label.counts --apply-log=true $srcdir/final.nnet "$feats" ark,t:output.txt

For question 2, are you trying to output frame-level or utterance-level outputs?

**Comment by madhavsund** [comment]
utterance-level output.
