### ISSUE TITLE
Integrating silence phone to phone-ctc

### ISSUE THREAD

**Issue by al-muammar** [srvk/eesen#45]
It seems for me that it would be really healthy to add `<SIL>` phone to phones (like `<SPACE>`), since ideologically `<blk>` label correspond to "I'm not sure what to output right now" or "phone is changing". And for me it seems that it is not a good practice to force it to make different tasks at the same time.

The problem with this approach is that nobody marks silence. That's why we need some basic alignments, extract silences from them and only then train the system. Are you going to develop these types of approaches?

**Comment by yajiemiao** [comment]
Adding silence is easy and conceptually makes more sense. However, the difficulty lies in the lack of alignment, i.e., transcripts which contain <SIL>. Of course we can get it by doing forced alignment with initial GMM models. However, this dependency makes the pipeline not end-to-end anymore, which conflicts to the goal of Eesen.
