### ISSUE TITLE
Trying tedlium demo(v1) and crashed when trainning on the first epoch

### ISSUE THREAD

**Issue by zhangjiulong** [srvk/eesen#56]
I used tedlium(110hours) data and  tried to runnrun_ctc_phn.sh and run_ctc_char.sh scripts.
But I got the error on the first epoch.

CUDA version is 7.5
GPU is NVIDIA GeForce GTX 970

the error part log as follows:

```
VLOG[1] (train-ctc-parallel:EvalParallel():ctc-loss.cc:182) After 35000 sequences (53.5094Hr): Obj(log[Pzx]) = -228.534   TokenAcc = 54.2553%
VLOG[1] (train-ctc-parallel:EvalParallel():ctc-loss.cc:182) After 36000 sequences (56.0337Hr): Obj(log[Pzx]) = -235.923   TokenAcc = 54.2852%
WARNING (train-ctc-parallel:MallocInternal():cuda-device.cc:658) Allocation of 18460 rows, each of size 2560 bytes failed,  releasing cached memory and retrying.
WARNING (train-ctc-parallel:MallocInternal():cuda-device.cc:665) Allocation failed for the second time.    Printing device memory usage and exiting
LOG (train-ctc-parallel:PrintMemoryUsage():cuda-device.cc:334) Memory used: 4142407680 bytes.
ERROR (train-ctc-parallel:MallocInternal():cuda-device.cc:668) Memory allocation failure
WARNING (train-ctc-parallel:Close():kaldi-io.cc:446) Pipe copy-feats scp:exp/train_char_l5_c320/train_local.scp ark:- | add-deltas ark:- ark:- | had nonzero return status 36096
ERROR (train-ctc-parallel:MallocInternal():cuda-device.cc:668) Memory allocation failure

[stack trace: ]
eesen::KaldiGetStackTrace()
eesen::KaldiErrorMessage::~KaldiErrorMessage()

```

Look forward your suggestion.

**Comment by fmetze** [comment]
This card only has 4Gb of memory, right? You may need to reduce the --frame-num-limit setting in the call to train_ctc_parallel.sh somewhat. 

> On May 26, 2016, at 7:16 AM, zhangjiulong notifications@github.com wrote:
> 
> I used tedlium(110hours) data and tried to runnrun_ctc_phn.sh and run_ctc_char.sh scripts.
> But I got the error on the first epoch.
> 
> CUDA version is 7.5
> GPU is NVIDIA GeForce GTX 970
> 
> the error part log as follows:
> 
> VLOG[1](train-ctc-parallel:EvalParallel%28%29:ctc-loss.cc:182) After 35000 sequences (53.5094Hr): Obj(log[Pzx]) = -228.534   TokenAcc = 54.2553%
> VLOG[1](train-ctc-parallel:EvalParallel%28%29:ctc-loss.cc:182) After 36000 sequences (56.0337Hr): Obj(log[Pzx]) = -235.923   TokenAcc = 54.2852%
> WARNING (train-ctc-parallel:MallocInternal():cuda-device.cc:658) Allocation of 18460 rows, each of size 2560 bytes failed,  releasing cached memory and retrying.
> WARNING (train-ctc-parallel:MallocInternal():cuda-device.cc:665) Allocation failed for the second time.    Printing device memory usage and exiting
> LOG (train-ctc-parallel:PrintMemoryUsage():cuda-device.cc:334) Memory used: 4142407680 bytes.
> ERROR (train-ctc-parallel:MallocInternal():cuda-device.cc:668) Memory allocation failure
> WARNING (train-ctc-parallel:Close():kaldi-io.cc:446) Pipe copy-feats scp:exp/train_char_l5_c320/train_local.scp ark:- | add-deltas ark:- ark:- | had nonzero return status 36096
> ERROR (train-ctc-parallel:MallocInternal():cuda-device.cc:668) Memory allocation failure
> 
> [stack trace: ]
> eesen::KaldiGetStackTrace()
> eesen::KaldiErrorMessage::~KaldiErrorMessage()
> 
> Look forward your suggestion.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen/issues/56

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by yajiemiao** [comment]
Reducing --frame-num-limit in your training script will solve this issue.
Also, try to use the latest version which resolves other complications with GPU memory.

**Comment by zhangjiulong** [comment]
yes it works!! thank all of you!!!

**Comment by mjhanphd** [comment]
I'm facing the same problem.
BTW, how much should I reduce --frame-num-limit to make it work, not losing too much efficiency?
For now, the only way I can guess is just decreasing that value little by little and checking if it works.

Bottom line: Is there any way to estimate the proper value for --frame-num-limit that is compatible with my working environment?

**Comment by fmetze** [comment]
I guess there is not really a practical way to compute it. You could maybe come up with a rule of thumb by running different values and observing the real memory usage during training, then extrapolating?
