### ISSUE TITLE
does eesen can manually select gpu id to run?

### ISSUE THREAD

**Issue by zhangjiulong** [srvk/eesen#61]
does eesen can manually select gpu id to run?

**Comment by fmetze** [comment]
Yes, it will respect the CUDA_VISIBLE_DEVICES environmental variable. You can set this to e.g. gpu1 for a particular job, and it will then use this GPU only.

> On Jun 15, 2016, at 4:24 AM, zhangjiulong notifications@github.com wrote:
> 
> does eesen can manually select gpu id to run?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/srvk/eesen/issues/61, or mute the thread https://github.com/notifications/unsubscribe/AEnA8T7XxiHTRgYUnJtVQ7lxuagqGPopks5qL7bVgaJpZM4I2HFN.

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by zhangjiulong** [comment]
@fmetze thanks very much I‘ll try

**Comment by zhangjiulong** [comment]
Hi I add 'export CUDA_VISIBLE_DEVICES=gpu1' to path.sh but it does not work

**Comment by fmetze** [comment]
try setting it to “1” instead of “gpu1” - or a respective value that is supported by your system, see e.g. http://www.acceleware.com/blog/cudavisibledevices-masking-gpus

> On Jun 20, 2016, at 4:23 AM, john notifications@github.com wrote:
> 
> Hi I add 'export CUDA_VISIBLE_DEVICES=gpu1' to path.sh but it does not work
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub https://github.com/srvk/eesen/issues/61#issuecomment-227079063, or mute the thread https://github.com/notifications/unsubscribe/AEnA8a6Mwltg-M--C3rmookMBdrWv49eks5qNk4VgaJpZM4I2HFN.

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by zhangjiulong** [comment]
@fmetze yes it works thx

**Comment by zhangjiulong** [comment]
after I set export CUDA_VISIBLE_DEVICES=1 the program run ok and use the right gpu，the gpu memory used increasing slowly.
But the ‘GPU-Util’ value is always zero.
If i delete the CUDA_VISIBLE_DEVICES=1 and the  ‘GPU-Util’ value is ok
