### ISSUE TITLE
eesen LSTM-CTC result in SWB?

### ISSUE THREAD

**Issue by chenzhehuai** [srvk/eesen#62]
hi
thanks for ur toolkit, and we are also doing some researches in CTC.

In the page below, we see BLSTM-CTC v.s. DNN-HMM & LSTM-HMM, which is reasonable.
Is there any LSTM-CTC result in SWB, with similar num of parameters?

https://github.com/srvk/eesen/blob/master/asr_egs/swbd/v1/RESULTS

thanks again!

**Comment by chenzhehuai** [comment]
we have seen in ur paper ICASSP2016.

**Comment by fmetze** [comment]
We currently have a model with a WER of 13.5% on SWBD (rather than 15.0%). 

It uses 33Mb rather than 42Mb, and uses projection layers. 

Does that help? Best, F.

> On Jun 17, 2016, at 4:30 AM, chenzhehuai notifications@github.com wrote:
> 
> we have seen in ur paper ICASSP2016.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/srvk/eesen/issues/62#issuecomment-226711686, or mute the thread https://github.com/notifications/unsubscribe/AEnA8du0coCOAODyAEOU8JR87nzgOihcks5qMlsSgaJpZM4I4Gbu.

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by yajiemiao** [comment]
if you meant unidirectional LSTM, it's 15% relatively worse than the bidirectional one

**Comment by yajiemiao** [comment]
sorry i didn't notice you've closed the thread
