### ISSUE TITLE
latttice－1best is not aligned

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#63]
Hi Yajie

Hope you well

I am very interested to obtain the correctly aligned phone sequence to word. But currently Eesen's lattice-1best.cc can only generate approximate alignment of word and its phone sequence. 
for example, the following output from lattice-1best:
0
0   1   21 3.79004,4.6815,1_1_1_1_1_1_1_2_2_2_2_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_9_1_1_1_1_1_1_1_1_39_1
1   2   62  0.0800781,0.134042,1_3_1_1_1_1_1_1_1_1_26_1_1_1_1_1_1_1_34_1_1
2   3   57  1.21191,8.98855,1_8_1_1_1_1_1_1_1_1_1_1_10_1_1_3_1_1_1_1_1_1_1_1_1_1_1_34_1_1_1_1_1_8_1_1_1_24_24_24_1_1
3   4   33  0.113281,0.192038,1_5_1_1_1_1_1_1_1_1_1_38_1_1_1_1_1_1_1_1
4   5   60  2.41016,8.13873,1_4_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_10_1_1_32_1_1_1_1_1_1_1_1_8_1_1_1_1_24_24_1_1_37_1_1_1_1_1_1_1_1_1_1_34_1_1_1_1_1_1_1_1_1_1_1_1_31_31_1_1_1_1_1_37_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_10_1_1_1_21_1_1_1_1_1_1_1_1_1_1_1_31_1_1_1_1_1_1_1_1_1_1_1_14_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_12_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1
5   3.00586,0,2
...............

the phone sequences are not exactly aligned to the word ( represent by int). 
I am very new to Kaldi and asr. from what I know, there is a kaldi function : lattice-word-align.cc can be used if we want an exact word-to-phoneseq alignment, but that function requires a final.mdl, which ctc doesn't have.

Could you please give me some hints to how to generate exact word-to-phoneseq alginment?

Best

**Comment by xfwu** [comment]
may be this one is a better example:
0
0   1   17  5.14551,2.63603,1_1_1_1_2_2_2_2_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_18_1_1_1_14_1_1_1_1_1_1_1_1_34_34_34_1_1_1_1_1_1
1   2   30  3.3584,0.0412467,1_1_25_1_21_1_1_1_1
2   3   57  1.39062,17.1739,1_1_1_1_1_1_1_1_1_1_1_1_1_1_1
3   4   33  0.113281,7.08899,
4   5   60  2.41016,6.8943,26_1_1_1_1_1_1_1_1_1_1_1_1_1_1_9_1_1_1_1_1_1_1_1_1_1_1_1_1_1_34_1_1_1_1_1_1_1_1_1_1_1_1_10_1_1_3_1_1_1_1_1_1_1_1_1_1_1_1_1_23_1_1_32_32_1_1_1_1_1_1_8_1_1_1_1_1_1_41_1_1_5_1_1_1_1_38_1_1_1_1_4_1_1_1_1_1_1_1_1_1_25_1_1_1_1_1_1_1_1_1_32_1_1_1_1_1_1_1_1_34_1_1_1_1_8_1_1_1_1_1_1_1_1_24_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1
5   3.00586,0,2_2

**Comment by yajiemiao** [comment]
You are right, lattice-word-align.cc from Kaldi is not applicable to Eesen. Also, developing such a lattice-word-align utility for Eesen is not straightforward, as the CTC states contain no word boundary information.

@naxingyu probably has more information regarding this?

**Comment by xfwu** [comment]
Hi Yajie

Thank you very much for the quick answer.

can I ask a further question: 
given the example above, I can see that although word number 2 and 3 do not have correct phone sequence aligned, but actually their phone sequences are appeared in the beginning of the word number 4's phone sequence. I checked a few other un-aligned cases, they all have such phenomenon. Can I assume that the total phone sequence does contain all the word phone sequences, therefor I can use a beamsearch-like skill to obtain the correct word-to-phone-alignment?

Thank you very much.

Best

**Comment by naxingyu** [comment]
@yajiemiao I think this is quite normal in Eesen. As you said, there is no word boundry information in CTC states. We tried using position dependent blanks to store word boundary information, but it seems harmful to the performance. @xfwu 's assumption that total phone sequence contrains the word sequence should be correct. But I don't think you can obtain the word-to-phone-alignment using beam search.

**Comment by xfwu** [comment]
Hi xingyu & yajie

Thank you very much for your reply.

Can I ask another naive question:

I found there are three main steps in latgen-faster.cc's DecodeUtteranceLatticeFaster() (calling the decoder/decoder-wrappers.cc)

1> decode()
2>GetBestPath()
3>GetRawLattice()

Could you please explain the relation between these three functions? I see there is a strong relation between the fist step and the third step, but what's the effect of applying the second step （GetRawLattice() ）.
In GetBestPath(), it also called GetRawLattice(). if it is only used for producing some debuging information, can I comment it out for better speed?

Also, what is the difference between the GetBestPath() in decoder-wrappers.cc and Lattice-1best.cc's output? I see the acoustic-factor and acoustic-scale times together to get acoustic-weight in Lattice-1best.cc, which seemed taking the same role as the acoustic-scale in latgen-faster.cc.

Thank you very much

Best

**Comment by naxingyu** [comment]
Decode() makes sure that you have a valid lattice to GetBestPath() and 
GetRawLattice(). In the latgen faster decoder, GetBestPath() and 
GetRawLattice() are not funtionally related. You can just remove the 
calling of GetRawLattice() if you don't want the state-level lattice, or 
remove the GetBestPath() otherwise.

X.

在 2016/6/29 20:59, Xiaofeng Wu 写道:

**Comment by xfwu** [comment]
Thank you very much. Sorry that I am still not fully understand.

Can I assume that GetBestPath() has the same performance as GetRawLattice() + Lattice-1best.cc ?

Best

**Comment by naxingyu** [comment]
I would say it is GetRawLattice() + lattice-best-path. But Yajie knows 
it better.

X.

在 2016/6/30 9:51, Xiaofeng Wu 写道:

**Comment by yajiemiao** [comment]
@xfwu Yes, your understanding is right, GetBestPath() is simply for generating debugging information, so that you can see some recognition outputs even if you are generating lattices

Applying lattice-best-path to lattices is equivalent to applying GetBestPath() directly, or applying decode-faster

**Comment by xfwu** [comment]
Hi Yajie & Xingyu

What I am currently trying is to decode on a class-based method. I need to run a second decoding to find out the correct phone sequence for the class holder. But given the current lattice-1best output, (or the ShortestPath) it is a little bit tricky. 
Because 1) I don't know the exact start point of each word
               2) there are phone repeat themselves consecutively. Some represents only one phone, but some represent 2 phones (like the t t in phrases like 'want to' ) 
Actually to do a DFS search upon the first decode result seemed a not very good idea, afterall, I don't want to run into multiple results.

Apologies for my rookie questions, I still don't understand why CTC can't generate a phone-to-word alignment. Since TLG has been combined, doesn't each word should be output at the beginning of its phone sequence?

Thanks a million

Xiaofeng

**Comment by yajiemiao** [comment]
It's difficult to get (correct) word boundaries because getting phone boundaries is difficult with the existing Eesen framework. In traditional GMM/DNN, if you've got a frame-level state sequence "a_4 a_4 a_5 a_5 a_5 b_1 b_1 b_1", you can immediately tell where the two phones are separated. However, for CTC, you might just get "a a # # # # # # b b b" (# is blank), and have no idea where to separate a and b, as all the blanks in between are not distinguishable. This is why the timing information is potentially wrong, although you do get alignments/timing information for each word.

**Comment by xfwu** [comment]
thank you very much！
