### ISSUE TITLE
about <eps>:<eps>

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#72]
Hi Yajie

I made a toy example to study the TLG.fst following the [link](http://vpanayotov.blogspot.ie/2012/06/kaldi-decoding-graph-construction.html)

I end up with the following TLG graph.
[TLG.pdf](https://github.com/srvk/eesen/files/375734/TLG.pdf)

From the pdf, I noticed an interesting thing: state 6 to state 14 has to pass the state 10, but the arc from 6 to 10 and the arc from 10 to 14 are the same as: "eps:eps". I think "eps:eps" represents that there is no input and there is no output. The reason why Eesen has to insert an intermediate state 10 there is the T.fst 
[T.pdf](https://github.com/srvk/eesen/files/375752/T.pdf)

is built following: "there has to be "eps:eps" arc both at the end and the beginning of each phone".

I think there won't be much speed loss by inserting this intermediate state, I just wonder if we delete the intermediate state, what would happen?

Thank you very much!

Best

**Comment by yajiemiao** [comment]
what does the : symbol mean in your post?

**Comment by xfwu** [comment]
Sorry, I updated the post it was using angular brackets. 
I tried to applied fstrmepsilon on the TLG.fst, it result in almost 2 times larger TLG.fst, but I did get some speed improvement (around 28% relative)

Best

**Comment by yajiemiao** [comment]
You can safely remove the <eps>:<eps>10<eps>:<eps> part in the FST. But I am not sure whether you can remove all the <eps>. Are you getting the same WER?

**Comment by xfwu** [comment]
Not exactly, but I would say they are 'significantly' alike in my test set (which is about 100 utterance)
