### ISSUE TITLE
how does fst prevent from generating shorter path

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#77]
Hi 

Sorry for this naive question... I did not see from Eesen's decoding code of this. I know in MT there is something like length-penalty...

thanks a lot

Best

**Comment by yajiemiao** [comment]
by default we don't have this penalty
please refer to our latest commit which applies lattice-add-penalty to penalize insertion of words 
https://github.com/srvk/eesen/pull/74/files

**Comment by xfwu** [comment]
thank you very much!!

Best
