### ISSUE TITLE
Convert eesen lattices to SLF lattices

### ISSUE THREAD

**Issue by antho-rousseau** [srvk/eesen#8]
Hi,

how one could convert eesen lattices to SLF lattices like in Kaldi using lattice-align-words and lattice-to-phone-lattice? Would it be possible?

Thanks!

**Comment by ghost** [comment]
eesen does not have these two utilities for now. Both of them require transition model which is obviously not available in eesen. That's why adapting them from kaldi could be much of a hassle. We will revisit this and figure out a way in the near future.

**Comment by antho-rousseau** [comment]
Hi Yajie,

thanks for your answer.

Actually it seems that the eesen-produced lattices are somewhat already phone-aligned, I'm currently trying to figure a way to produce these HTK lattices but as you said that's kind of a hassle. I'm looking forward to your eesen enhancements. Very nice tool by the way!

Best,
Anthony Rousseau
