### ISSUE TITLE
setting output neurons

### ISSUE THREAD

**Issue by madhavsund** [srvk/eesen#80]
We are trying eesen for OCR.
We have a dataset with labels marked 1 to 320 . but some of the labels are not seen in training and testing set.only 218 labels are seen.
the question is 
what would be the number of output neurons  either 218 or 320?

**Comment by yajiemiao** [comment]
You should use 320 labels

**Comment by madhavsund** [comment]
thank you...
it works. my network is two layer with 320 neurons, but the convergence is very slow.
what could be  the reasons
1. my inputs are binary images. whether  cmvn is required ?
2. due to frame skipping. if so, kindly say where to change the parameter
3. any parameter is specifically set for speech in eesen

**Comment by madhavsund** [comment]
the problem was with parameters...
now it is working
