### ISSUE TITLE
does eesen has plan for SMBR?

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#82]
Hi Yajie

Just wondering if Eesen has this implementation plan?
Thank you very much

Best

**Comment by yajiemiao** [comment]
Hi, discriminative training of CTC models is on our agenda. But we don't have an exact time when it can be delivered.

**Comment by xfwu** [comment]
Thank you very much!

I have a few questions regarding MPE CTC.

1> Traditional MPE/sMBR employ posterior probabilities like in the SMBR paper 

> Sequence-discriminative training of deep neural  networks

 Equation 8
 But CTC employs Maximum Likelihood Training. Can I use p(l|x) in 

> Connectionist Temporal Classification: Labelling Unsegmented Sequence Data with Recurrent Neural Networks

 Equation 15 to replace the P(O|S) in SMBR paper Equation 8?

2>P(W) (in SMBR paper equation 15) supposed to be the language model of the training data, right? What if the training data and the real test data are in different domain, I still need to use the language model of the training data?

Thank you very much

**Comment by xfwu** [comment]
Hi Yajie

Sorry to bother you with another question:

The basic steps of discriminative training is 

> 1. get the denlattice
> 2. get the alignment
> 3. do the discriminative training

For step 1. my understanding is the CTC lattice generated by latgen-faster
For step 2. I don't have very clear clue how to get the aligment

Could you please give me some guidance?

Best
