### ISSUE TITLE
out of vocabulary detection

### ISSUE THREAD

**Issue by madhavsund** [srvk/eesen#83]
How to detect Out of Vocabulary words during recognition?

**Comment by yajiemiao** [comment]
They cannot be detected and added automatically. If you model characters as CTC targets, that could be easier, as you don't need to get the pronunciation for OOV words.

**Comment by madhavsund** [comment]
Whether it is possible as in cmusphinx
http://cmusphinx.sourceforge.net/wiki/sphinx4:rejectionhandling&ei=UrFa_XoW&lc=en-IN&s=1&m=904&host=www.google.co.in&ts=1470582605&sig=AKOVD64WMt4E1w7AxaONOZqWIzhwdttIZA

**Comment by yajiemiao** [comment]
not really

**Comment by madhavsund** [comment]
ok.
1. how to get the confidence score of each recognized word.
2. how to get the N- best results from lattice

**Comment by fmetze** [comment]
We added code to the TEDLIUM recipe to do this, see asr_egs/tedlium/v1/local/score_sclite.sh

**Comment by riebling** [comment]
Closing since no response in 3 months, assuming proposed solution acceptable.
