### ISSUE TITLE
live mode recognition

### ISSUE THREAD

**Issue by Bhee** [srvk/eesen#84]
I would like to test the model with live utterance (by live recording ) instead of batch mode,
1. whether eesen support live mode?  
2. if not how to load a model once and decode  each utterance

**Comment by fmetze** [comment]
Please look [here](https://github.com/srvk/eesen/issues/64), the transcriber can load multiple utterances easily.

Online/ live recognition would be great to have, but it is a lot of engineering - anyone up for it?
