### ISSUE TITLE
force alignment

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#92]
What is the best way to do a force alignment/decoding in Eesen?
I want to generate the alignment of the reference, given the softmaxed output

Best

**Comment by yajiemiao** [comment]
I just checked in new updates to do so. The high-level script is align_ctc_single_utt.sh
Note that currently we can only generate alignments utterance by utterance, rather than in a batch mode (as in Kaldi)

**Comment by xfwu** [comment]
thank you very much!

My understanding is that this scripts can generate a lattice with a "weak language model".. then get the best path out of the lattice.

I presume that because it uses a "weak language model", it is very likely that the correct path (reference ) is included in the lattice. Therefore, for mpe training, this correct path in the lattice can be used as the nominator. right?

Best

**Comment by xfwu** [comment]
Thank you very much!

I presume that the uttdata-dir stores only one utterance's reference, therefore the G.fst generated out of this reference will be used to generate only a very compact lattice, and the the 1best path found in that lattice is actually the reference!!

this is very cool!

Best

**Comment by yajiemiao** [comment]
Yep, your understanding is correct.
