### ISSUE TITLE
where is the code to generate the prior of states

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#96]
Hi Yajie

In your paper section “3.2: posterior normalization" you mentioned there are method to generate the priors.

I could not find it in Eesen, also in the lattice-faster-decoder.cc which should use them I guess?

BTW, since CTC output are so peaky, and so many blank peaked in each frame, what is the best way to do smbr?

Best

**Comment by fmetze** [comment]
The train_ctc_parallel.sh script contains the following call (or something equivalent - depending on the exact recipe that you are running):

# Compute the occurrence counts of labels in the label sequences. These counts will be used to

# derive prior probabilities of the labels.

gunzip -c $dir/labels.tr.gz | awk '{line=$0; gsub(" "," 0 ",line); print line " 0";}' | \
  analyze-counts --verbose=1 --binary=false ark:- $dir/label.counts >& $dir/log/compute_label_counts.log || exit 1
##

**Comment by xfwu** [comment]
thank you very much!

best
