### ISSUE TITLE
what is the difference between tokens.txt and units.txt

### ISSUE THREAD

**Issue by zhangjiulong** [srvk/eesen#97]
whichi file to use when decoding to get phone list.

**Comment by fmetze** [comment]
Do you want the sequence of phones that the acoustic model would compute without a language model? The same that is computed during validation in the training step?

tokens.txt contains the tokens of the FST, with blank and disambiguation tokens, while units.txt contains the list of phones.

**Comment by zhangjiulong** [comment]
as in the [issues98](https://github.com/srvk/eesen/issues/98) why units.txt do not contains blank id?

**Comment by fmetze** [comment]
the blank is implicit - you don't specify it, it appears between all phones, but it is not a unit that gets used in the computation of the objective function.

**Comment by zhangjiulong** [comment]
Thanks for your replay, I will try to understand.
